In [113]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from Preprocessing import preprocessing
from Preprocessing import pre_bird_category

from MLP import MLP

In [114]:
all_data = pd.read_csv('birds.csv')
all_data.head()

gender  body_mass  beak_length  beak_depth  fin_length bird category
0    male       3750         39.1        18.7         181             A
1  female       3800         39.5        17.4         186             A
2  female       3250         40.3        18.0         195             A
3  female       3500         39.6        17.7         186             A
4  female       3450         36.7        19.3         193             A

In [115]:
# preprocessing
preprocessing(data=all_data, classes=['A', 'B', 'C']) # A->0 , B->1 , C->2

# Class A Portion
Class_A = all_data.iloc[0:50, :]
# Class B Portion
Class_B = all_data.iloc[50:100, :]
# Class C Portion
Class_C = all_data.iloc[100:150, :]

# Shuffling portions
Class_A = Class_A.sample(frac=1, random_state=42).reset_index(drop=True)
Class_B = Class_B.sample(frac=1, random_state=42).reset_index(drop=True)
Class_C = Class_C.sample(frac=1, random_state=42).reset_index(drop=True)

Column: gender
Column: body_mass
Column: beak_length
Column: beak_depth
Column: fin_length
Column: bird category


In [116]:
# Data Slicing (Training & Test) for each class

TrainClass_A = Class_A.iloc[0:30, :]
TestClass_A = Class_A.iloc[30:50, :]

TrainClass_B = Class_B.iloc[0:30, :]
TestClass_B = Class_B.iloc[30:50, :]

TrainClass_C = Class_C.iloc[0:30, :]
TestClass_C = Class_C.iloc[30:50, :]


# Compining Train samples of each class
train = pd.concat([TrainClass_A, TrainClass_B, TrainClass_C])
# Compining Test samples of each class
test = pd.concat([TestClass_A, TestClass_B, TestClass_C])


# Shuffling Train and Test data
train = train.sample(frac=1, random_state=42).reset_index(drop=True)
test = test.sample(frac=1, random_state=42).reset_index(drop=True)

# split to X and y
Xtrain = train.iloc[:, :-1]
ytrain = train.iloc[:, -1]

Xtest = test.iloc[:, :-1]
ytest = test.iloc[:, -1]

# ytrain.shape
train

gender  body_mass  beak_length  beak_depth  fin_length  bird category
0      0.0   0.541667     0.447059    0.071429    0.724138              1
1      1.0   0.305556     0.184314    0.488095    0.137931              0
2      0.0   0.500000     0.470588    0.011905    0.672414              1
3      0.0   0.277778     0.505882    0.500000    0.224138              2
4      1.0   0.305556     0.176471    0.964286    0.327586              0
..     ...        ...          ...         ...         ...            ...
85     0.0   0.430556     0.309804    0.845238    0.310345              0
86     1.0   0.375000     0.701961    0.595238    0.500000              2
87     1.0   0.284722     0.729412    0.797619    0.431034              2
88     0.0   0.222222     0.215686    0.547619    0.241379              0
89     0.0   0.402778     0.309804    0.047619    0.655172              1

[90 rows x 6 columns]

In [117]:
# best_weights = model.fit(Xtrain, ytrain)

# print("\nBest Weights : ", best_weights)
# loss, weights = model.load_model()
# print(f"loss : {loss}, weights : \n {weights}")
# print(f"best_weights : {best_weights}")


In [118]:
# best_weights = [[[ 0.64819162,  0.38316173, -0.15428586],
#        [ 0.52363071,  0.56380712, -0.35065961],
#        [-0.33944906, -5.43035068,  2.00292476],
#        [-0.64123229,  1.30669582, -0.88756273],
#        [ 0.20521493, -0.67718077,  1.86215213],
#        [-1.68937042,  0.95124276, -0.08434086]], 
# [[ 1.53327522,  0.49088125,  0.68761451, -0.47035645],
#        [-1.23922634, -2.26306557, -0.01011435, -5.24708996],
#        [ 0.21467054,  0.75242651,  1.17180317,  3.53507088],
#        [-0.542813  , -0.16096332, -0.40433515, -0.08318577]], 
# [[-0.00526994,  0.91841773, -0.23300637],
#        [-0.68513078,  2.14802909,  1.22918329],
#        [-0.58032858,  0.02079821, -0.88279239],
#        [ 2.90625824,  3.32756523,  4.24387787],
#        [ 0.84686752, -1.39186271, -0.57016828]]]

# model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest, weights=best_weights)

# print(model.predict([0.0	,0.277778	,0.505882	,0.500000	,0.224138	]))

In [119]:
# model = MLP([5], 0.001, activation='tanh', epochs=5000)

# best_weights = model.fit(Xtrain, ytrain)
# print("\nBest Weights : ", best_weights)

# best_weights2 = model.fit(Xtrain, ytrain)
# print("\nBest Weights : ", best_weights2)


In [120]:
# we = [np.array([[ 0.64819162,  0.38316173, -0.15428586],
#        [ 0.52363071,  0.56380712, -0.35065961],
#        [-0.33944906, -5.43035068,  2.00292476],
#        [-0.64123229,  1.30669582, -0.88756273],
#        [ 0.20521493, -0.67718077,  1.86215213],
#        [-1.68937042,  0.95124276, -0.08434086]]), 
# np.array([[ 1.53327522,  0.49088125,  0.68761451, -0.47035645],
#        [-1.23922634, -2.26306557, -0.01011435, -5.24708996],
#        [ 0.21467054,  0.75242651,  1.17180317,  3.53507088],
#        [-0.542813  , -0.16096332, -0.40433515, -0.08318577]]), 
# np.array([[-0.00526994,  0.91841773, -0.23300637],
#        [-0.68513078,  2.14802909,  1.22918329],
#        [-0.58032858,  0.02079821, -0.88279239],
#        [ 2.90625824,  3.32756523,  4.24387787],
#        [ 0.84686752, -1.39186271, -0.57016828]])]



In [121]:
# model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest, weights=best_weights2)

## save sigmoid 

In [ ]:
model = MLP([3,4], 0.01, activation='sigmoid', epochs=1000)
model.fit(Xtrain, ytrain)
#model.save("sigmoid_weights4.txt")
model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest)
#model.load()


completed 100%Training Accuracy: 86.67%
Testing Accuracy: 91.67%
Training Confusion Matrix:
[[20  0 10]
 [ 0 30  0]
 [ 2  0 28]]
Testing Confusion Matrix:
[[15  0  5]
 [ 0 20  0]
 [ 0  0 20]]


## load sigmoid_weights

In [ ]:
# model = MLP([3,4], 0.01, activation='sigmoid', epochs=1000)
# #model.fit(Xtrain, ytrain)
# #model.save("sigmoid_weights4.txt")
# model.load("sigmoid_weights3.txt")
# model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest)



Training Accuracy: 93.33%
Testing Accuracy: 88.33%
Training Confusion Matrix:
[[30  0  0]
 [ 0 30  0]
 [ 6  0 24]]
Testing Confusion Matrix:
[[20  0  0]
 [ 0 20  0]
 [ 5  2 13]]


In [ ]:
# seed = [np.array([[ 0.69506727, -0.48667016,  0.26852711],
#        [ 0.16406203,  0.83477334, -0.99975602],
#        [ 0.16063209,  0.27740719, -0.36662438],
#        [ 0.07552176, -0.27534146,  0.65307344],
#        [ 0.24160272,  0.82922276,  0.81540669],
#        [ 0.59949699,  0.80282486,  0.27493933]]), np.array([[ 0.03065245,  0.32238248,  0.97783286, -0.50961645],
#        [ 0.98635309, -0.08478647,  0.09932797, -0.56563766],
#        [ 0.44839273,  0.00998966, -0.69873867,  0.79362428],
#        [ 0.56171304, -0.57550867, -0.45102524,  0.99946301]]), np.array([[ 0.21680518, -0.75688903,  0.57178616],
#        [-0.42424101,  0.10064444, -0.529735  ],
#        [ 0.68066055,  0.43603743,  0.75536626],
#        [ 0.40871426, -0.82451724, -0.92979592],
#        [-0.72846831,  0.09768811, -0.23434191]])]
# model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest, seed)

In [124]:
# model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest)

## tanh model 

In [ ]:

model = MLP([5], 0.001, activation='tanh', epochs=5000)
model.fit(Xtrain, ytrain)
#model.save("tanh2.txt")
model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest)


completed 100%Training Accuracy: 98.89%
Testing Accuracy: 98.33%
Training Confusion Matrix:
[[30  0  0]
 [ 0 30  0]
 [ 1  0 29]]
Testing Confusion Matrix:
[[20  0  0]
 [ 0 20  0]
 [ 1  0 19]]


In [126]:
# model = MLP([3,4], 0.01, activation='sigmoid', epochs=1)

In [127]:
# model = MLP(layers=[5, [3,4], 3], learning_rate=0.01, activation='sigmoid', epochs=1000)
# best_weights = model.fit(Xtrain, ytrain)
# model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest)

In [128]:
X = Xtrain

X_sample = X.iloc[0].values.reshape(1, -1)

In [129]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [130]:
weights =  [np.array([[ 0.0610259 , -0.11868473,  0.19167696],
       [ 0.09293665,  0.00103983, -0.13324832],
       [-0.00237433,  0.01167979,  0.01780459],
       [-0.03013405,  0.03615819, -0.08002573],
       [-0.06259181, -0.21435596, -0.0503132 ]]), np.array([[ 0.00709197, -0.08306363, -0.0095609 ,  0.02822289],
       [ 0.19463308,  0.06623523, -0.0424625 ,  0.09085919],
       [-0.01691818, -0.1171061 , -0.04754496, -0.07305191]]), np.array([[-0.05476062,  0.02802921, -0.02102756],
       [-0.05706505,  0.01814017,  0.01677369],
       [ 0.13903822,  0.21813122,  0.11241118],
       [ 0.00651469, -0.10144174, -0.2170584 ]])]


biases =  [np.array([[ 0.26423625,  0.110432  , -0.10540333]]), 
           np.array([[ 0.00130979, -0.09972528,  0.06601507,  0.11844253]]), 
           np.array([[-0.27820958, -0.05036378, -0.05838289]])]

In [131]:
def forward2(X):    
    # Forward pass
    activations = [X]
    for w, b in zip(weights, biases):
        activations.append(sigmoid(np.dot(activations[-1], w) + b))
    print(activations)
    # return activations



In [132]:
weights2 = [np.array([[ 0.0610259 , -0.11868473,  0.19167696],
       [ 0.09293665,  0.00103983, -0.13324832],
       [-0.00237433,  0.01167979,  0.01780459],
       [-0.03013405,  0.03615819, -0.08002573],
       [-0.06259181, -0.21435596, -0.0503132 ],
       [ 0.26423625,  0.110432  , -0.10540333]]), 
       
       np.array([[ 0.00709197, -0.08306363, -0.0095609 ,  0.02822289],
       [ 0.19463308,  0.06623523, -0.0424625 ,  0.09085919],
       [-0.01691818, -0.1171061 , -0.04754496, -0.07305191],
       [ 0.00130979, -0.09972528,  0.06601507,  0.11844253]]), 
       
       np.array([[-0.05476062,  0.02802921, -0.02102756],
       [-0.05706505,  0.01814017,  0.01677369],
       [ 0.13903822,  0.21813122,  0.11241118],
       [ 0.00651469, -0.10144174, -0.2170584 ],
       [-0.27820958, -0.05036378, -0.05838289]])]

In [133]:
def forward1(X):
    activations = [X]
    layersNets = []
    for i in range(len(weights2)):
        activations[i] = np.array(activations[i]).reshape(1, -1)
        CurrentLayerNets = np.dot(activations[i], weights2[i])
        layersNets.append(CurrentLayerNets)
        CurrentLayerNets = sigmoid(CurrentLayerNets)
        # # Apply activation function (sigmoid for hidden layers, no activation for output layer)
        if i != len(weights2) - 1:  # If not the output layer
            # Add bias to the next layer input
            CurrentLayerNets = np.append(CurrentLayerNets, 1)
        # Append the result to the activations list
        activations.append(CurrentLayerNets)    
    print(activations)
    # return activations

In [134]:
# forward2(X_sample)


In [135]:
# X_sample = np.append(X_sample, 1)
# forward1(X_sample)