In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from Preprocessing import preprocessing
from Preprocessing import pre_bird_category

from MLP import MLP

In [2]:
all_data = pd.read_csv('birds.csv')
all_data.head()

gender  body_mass  beak_length  beak_depth  fin_length bird category
0    male       3750         39.1        18.7         181             A
1  female       3800         39.5        17.4         186             A
2  female       3250         40.3        18.0         195             A
3  female       3500         39.6        17.7         186             A
4  female       3450         36.7        19.3         193             A

In [3]:
# preprocessing
preprocessing(data=all_data, classes=['A', 'B', 'C']) # A->0 , B->1 , C->2

# Class A Portion
Class_A = all_data.iloc[0:50, :]
# Class B Portion
Class_B = all_data.iloc[50:100, :]
# Class C Portion
Class_C = all_data.iloc[100:150, :]

# Shuffling portions
Class_A = Class_A.sample(frac=1, random_state=42).reset_index(drop=True)
Class_B = Class_B.sample(frac=1, random_state=42).reset_index(drop=True)
Class_C = Class_C.sample(frac=1, random_state=42).reset_index(drop=True)

Column: gender
Column: body_mass
Column: beak_length
Column: beak_depth
Column: fin_length
Column: bird category


In [4]:
# Data Slicing (Training & Test) for each class

TrainClass_A = Class_A.iloc[0:30, :]
TestClass_A = Class_A.iloc[30:50, :]

TrainClass_B = Class_B.iloc[0:30, :]
TestClass_B = Class_B.iloc[30:50, :]

TrainClass_C = Class_C.iloc[0:30, :]
TestClass_C = Class_C.iloc[30:50, :]


# Compining Train samples of each class
train = pd.concat([TrainClass_A, TrainClass_B, TrainClass_C])
# Compining Test samples of each class
test = pd.concat([TestClass_A, TestClass_B, TestClass_C])


# Shuffling Train and Test data
train = train.sample(frac=1, random_state=42).reset_index(drop=True)
test = test.sample(frac=1, random_state=42).reset_index(drop=True)

# split to X and y
Xtrain = train.iloc[:, :-1]
ytrain = train.iloc[:, -1]

Xtest = test.iloc[:, :-1]
ytest = test.iloc[:, -1]

# ytrain.shape
train

gender  body_mass  beak_length  beak_depth  fin_length  bird category
0      0.0   0.541667     0.447059    0.071429    0.724138              1
1      1.0   0.305556     0.184314    0.488095    0.137931              0
2      0.0   0.500000     0.470588    0.011905    0.672414              1
3      0.0   0.277778     0.505882    0.500000    0.224138              2
4      1.0   0.305556     0.176471    0.964286    0.327586              0
..     ...        ...          ...         ...         ...            ...
85     0.0   0.430556     0.309804    0.845238    0.310345              0
86     1.0   0.375000     0.701961    0.595238    0.500000              2
87     1.0   0.284722     0.729412    0.797619    0.431034              2
88     0.0   0.222222     0.215686    0.547619    0.241379              0
89     0.0   0.402778     0.309804    0.047619    0.655172              1

[90 rows x 6 columns]

In [5]:
model = MLP([3,4], 0.01, activation='sigmoid', epochs=1000)
model.fit(Xtrain, ytrain)

completed 100%least total loss:  44.01057638089732
Best weights:  [array([[ 0.64819162,  0.38316173, -0.15428586],
       [ 0.52363071,  0.56380712, -0.35065961],
       [-0.33944906, -5.43035068,  2.00292476],
       [-0.64123229,  1.30669582, -0.88756273],
       [ 0.20521493, -0.67718077,  1.86215213],
       [-1.68937042,  0.95124276, -0.08434086]]), array([[ 1.53327522,  0.49088125,  0.68761451, -0.47035645],
       [-1.23922634, -2.26306557, -0.01011435, -5.24708996],
       [ 0.21467054,  0.75242651,  1.17180317,  3.53507088],
       [-0.542813  , -0.16096332, -0.40433515, -0.08318577]]), array([[-0.00526994,  0.91841773, -0.23300637],
       [-0.68513078,  2.14802909,  1.22918329],
       [-0.58032858,  0.02079821, -0.88279239],
       [ 2.90625824,  3.32756523,  4.24387787],
       [ 0.84686752, -1.39186271, -0.57016828]])]


In [6]:
model.calculate_accuracy_and_confusion_matrix(Xtrain, ytrain, Xtest, ytest)

# print(model.predict([0.0	,0.277778	,0.505882	,0.500000	,0.224138	]))

Training Accuracy: 78.89%
Testing Accuracy: 80.00%
Training Confusion Matrix:
[[30  0  0]
 [ 1 16 13]
 [ 5  0 25]]
Testing Confusion Matrix:
[[20  0  0]
 [ 0 10 10]
 [ 2  0 18]]
